### ISSUE TITLE
[EPIC] Cortex Alertmanager as a notificaiton backend

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1150]
## Acceptance criteria:

- [ ] Opni Alerting deploys a CortexAlertManager cluster
- [ ] Guarantee HA state is consistent
- [ ] Alerts & messages are dispatched on a per-cluster basis
- [ ] Router configurations are built on a per-cluster basis
- [ ] AlertManager adapter can proxy requests to AlertManager through CortexAPI
- [ ] `Sidecar Syncer` server implements an adapter to Cortex AlertManager

**Comment by alexandreLamarre** [comment]
We require a fork of cortex to enable alertmanager to run on its own, cortex has a built in assumption that the distributor handles knowledge of tenant ids. So while the apis and functionality is separate for alertmanager it has to be connected to distributor + ingester to have knowledge of any tenant ids.

**Comment by alexandreLamarre** [comment]
The main advantage gained from using cortex is to have a consistent HA state, so I'd rather pivot to implementing a gossip ring, similar to cortex, into the embedded alertmanager we already use to get that functionality out of it.

**Comment by alexandreLamarre** [comment]
The other items in this epic are still relevant to separating concerns of the opni specific components, which will be required for many of the other OEPs for alerting.
