### ISSUE TITLE
[EPIC] Sync Downstream Prometheus Rules

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1499]
[Associated OEP](https://github.com/rancher/opni/blob/main/enhancements/alerting/20230126-sync-prometheus-rules.md)

Acceptance Criteria:
- [ ] Configurable Alerting Plugin,  #1498 
- [ ] Group Alert Conditions into individual buckets, #1500 
- [ ] Rule discovery mechanism, #1502
- [ ] Automatically apply Prometheus alerting rules, #1501
