### ISSUE TITLE
[EPIC] Logging & Alerting Integration

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1509]
[Associated OEP](https://github.com/rancher/opni/blob/main/enhancements/alerting/20230216-alerting-with-opensearch.md)

## Acceptance Criteria

- [ ] Logging Admin APIs for managing OpenSeachMonitors
- [ ] AlertManager Proxy for Opni-Alerting `Destination`  
- [ ] Add a Sync task to alerting sync loop for making sure Opni-alerting `Destination` object is always present
- [ ] CRUD Generic open search query Alarm Spec
- [ ] Alarm Status API implementation for Monitors
- [ ] Sync task for syncing alarm & monitor status
